# Tap repositories and their packages
tap 'homebrew/dupes'
brew 'apple-gcc42'
brew 'screen'
tap 'rcmdnk/file'
brew 'brew-file'

# Fonts
# 2016/12/24 現在下記方法でうまくパッチの当たった font ができない
# tap 'sanemat/font'
# brew 'ricty', args: ['vim-powerline']

# Cask packages
cask 'google-chrome'
cask '1password'
cask 'amethyst'
cask 'google-japanese-ime'
cask 'slack'
cask 'flux'
cask 'dropbox'

# Other Homebrew packages
brew 'autoconf'
brew 'automake'
brew 'boost'
brew 'cabextract'
brew 'ccache'
brew 'cloog'
brew 'cmake'
brew 'cmigemo'
brew 'convmv'
brew 'ctags'
brew 'direnv'
brew 'eigen'
brew 'fontconfig'
brew 'freetype', args: ['universal']
brew 'gdbm'
brew 'geoip'
brew 'git-flow'
brew 'gmp'
brew 'gnu-sed'
brew 'gnupg'
brew 'gnutls'
brew 'gradle'
brew 'imagemagick'
brew 'isl'
brew 'jasper', args: ['universal']
brew 'jpeg', args: ['universal']
brew 'libgpg-error'
brew 'libicns', args: ['universal']
brew 'libksba'
brew 'libmpc'
brew 'libpng', args: ['universal']
brew 'libtasn1', args: ['universal']
brew 'libtiff', args: ['universal']
brew 'libtool'
brew 'libyaml'
brew 'little-cms'
brew 'lua'
brew 'lv'
brew 'lynx'
brew 'mecab'
brew 'mecab-ipadic'
brew 'mobile-shell'
brew 'mosh'
brew 'mpfr'
brew 'mysql'
brew 'nettle'
brew 'nkf'
brew 'node'
brew 'oniguruma'
brew 'openssl'
brew 'p11-kit', args: ['universal']
brew 'peco'
brew 'pkg-config'
brew 'protobuf'
brew 'python'
brew 'qt'
brew 'rbenv'
brew 'readline'
brew 'ruby-build'
brew 'sqlite'
brew 'tbb'
brew 'thrift'
brew 'tree'
brew 'tmux'
brew 'vim', args: ['with-lua']
brew 'wine'
brew 'winetricks'
brew 'xz'
brew 'yasm'
brew 'z'
